services:
  - type: worker
    name: telegram-message-bot
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: TELEGRAM_API_ID
        sync: false
      - key: TELEGRAM_API_HASH
        sync: false
      - key: TELEGRAM_PHONE_NUMBER
        sync: false
      - key: SESSION_STRING
        sync: false
    plan: starter
